### ISSUE TITLE
Hat blocks should be callback-based, rather than polling-based

### ISSUE THREAD

**Issue by bobbybee** [LLK/scratch-extension-docs#10]
I'm not certain about the semantics for this; perhaps there is something like ext.trigger('greenFlag'). In any event, it would be particularly helpful in large extensions.

**Comment by liam4** [comment]
```javascript
ext.currentTrigger = null;

ext.getsEvent = function(which) {
    if (ext.currentTrigger === which) {
        ext.currentTrigger = null;
        // Do stuff
    }
};
ext.sendsEvent = function(which) {
    ext.currentTrigger = which;
};

ext.descriptor = {
    blocks: [
        ['h', 'when event %s sent', 'getsEvent', 'evt1']
        [' ', 'send event %s', 'sendsEvent', 'evt1']
    ]
};
```
As for "special" events such as what could be `'greenFlag'`, I'm not sure how you would send those. Probably like you said, `ext.trigger("special")`?

_Note - not tested, but should work.. :P_

**Comment by bobbybee** [comment]
@liam4 That's exactly the kind of code I'm hoping to avoid..

**Comment by liam4** [comment]
@bobbybee I see what you mean, but while they don't implement it, it'll work. :P

**Comment by sclements** [comment]
that's an interesting idea which we may implement at some point. The current implementation supports having hat blocks that accept arguments and we wanted that flexibility. For example, you can currently put a reporter from one extension into a hat block argument of another extension.

**Comment by rschamp** [comment]
@bobbybee Thanks for the suggestion! We have moved the content in this repo to https://github.com/LLK/scratchx/, would you please re-open this feature request on that repo?
