### ISSUE TITLE
Can not poll data from HID if there is no data returned. 

### ISSUE THREAD

**Issue by DeqingSun** [LLK/scratch-extension-docs#11]
In scratch_ext.js, extension will disconnect if there is no data read. However, The extension has no ideas when data comes from HID. So we need to keep polling even there is no data. Scratch shouldn't disconnect just because there is nothing to read.

        this.read = function(len) {
            if(!dev) return null;
            if(!len) len = 65;
            var data = dev.read(len);
            if(window.ActiveXObject) data = data(len);
            if(data.byteLength == 0) disconnect();
            return data;
        };

**Comment by DeqingSun** [comment]
Update.
Looks like if there an existing package received, I can poll it for multiple times. 
But if I poll before the first package, device will be disconnected.

**Comment by rschamp** [comment]
@DeqingSun Thanks for the report. We have moved the content in this repo to https://github.com/LLK/scratchx/, would you please re-open this issue on that repo?
