### ISSUE TITLE
Extension blocks no longer loaded when an .sb2 file is uploaded

### ISSUE THREAD

**Issue by MrYsLab** [LLK/scratch-extension-docs#12]
If I go to the More Blocks/Add an Extension/My Extensions and I load my extension, the blocks are shown correctly.

However, if I save the blocks to an .sb2 project, when I load that project, the blocks do not load.

This is new behavior. 

Have JavaScript extensions been disabled when loading from a .sb2 file?

**Comment by khanning** [comment]
I'm not able to reproduce this issue. Can you please confirm the steps you are taking?

Here are the steps I tested:
1. Create a new project
2. Attach a JS extension using the "Add an Extension" > "My Extensions" > "New from File..." option
3. Click the extension title dropdown and choose "Upload to server" 
4. Save the project
5. Use "File" > "Download to your computer" to download the .sb2 file
6. Upload the .sb2 file to Scratch on another machine/browser (not logged in)
7. The extension blocks are visible under the "More Blocks" tab

**Comment by MrYsLab** [comment]
@khanning I tried using projects that were created and saved back in november. They loaded the extension blocks until recently. 

I added "new" extensions by changing the "register" string, but did not change the exension other than that. That does load now.

So something definitely changed. Also, I can no longer remove an old extension. Again, things have changed.

I will close the issue.
