### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MrYsLab** [LLK/scratch-extension-docs#3]
Would it be possible when specifying the block text in the .js file to also specify a block color?

I am writing an extension that will have similar functionality for several hardware devices and would like to classify/separate the device types by color. 

Also, it would be nice to be able to draw a separator line between any given blocks so that "classes" of extension blocks would be more apparent.

**Comment by liam4** [comment]
.. bump? I think that this would be great. For example..

```javascript
var descriptor = {
    blocks: [/* ... */],
    menus: {/* ... */},
    url: /* ... */,
    color: [23, 57, 80]
    // [hue, saturation, brightness]
};
```

**Comment by shacharoz** [comment]
separator +1 vote

colors: not as important. but definitely not like liam suggested. because this would not allow painting blocks with different colors. if we're adding that option, it should be per block and not for the whole extension.

**Comment by liam4** [comment]
Oh, right, hmm.. how would we do that..

```javascript
var descriptor = {
    blocks: [
        [30, 30, 30], // Assign the following blocks to the color H30 S30 B30
        // ...
        [80, 20, 80], // Assign the following blocks to the color H80 S20 B80
        // ...
    ]
};
```
Or perhaps..
```javascript
var descriptor = {
    blocks:

**Comment by liam4** [comment]
Oh, right, hmm.. how would we do that..

```javascript
var descriptor = {
    blocks: [
        [30, 30, 30], // Assign the following blocks to the color H30 S30 B30
        // ...
        [80, 20, 80], // Assign the following blocks to the color H80 S20 B80
        // ...
    ]
};
```
Or perhaps..
```javascript
var descriptor = {
    blocks: [
        [' ', 'hello', 'helloFunc', [80, 20, 80]],
        ['r', 'args %s', 'argsFunc', "Hi there", [80, 40, 80]],
        ['b', 'args %s', 'argsFunc', undefined, [80, 60, 80]],
        // ...
    ]
}
```
I'm really not sure what would be best - perhaps a combination of both? :P

**Comment by ealgase** [comment]
Great idea on both!

**Comment by liam4** [comment]
And separators would work the same way as the spacer:

**Comment by ealgase** [comment]
Using
['-'],
will make a space between blocks, @liam4

**Comment by ealgase** [comment]
And a separator could be like this:
['_'],

**Comment by liam4** [comment]
Ah, yes, that's true. I forgot. :P

**Comment by rschamp** [comment]
Thanks all for the suggestions! We have moved the content in this repo to https://github.com/LLK/scratchx/, if you wouldn't mind, could you re-open your feature request on that repo?

When you do, please separate the request for separators from the request for color configurability so we can address them individually.
