### ISSUE TITLE
HID device does not support choosing Interface

### ISSUE THREAD

**Issue by DeqingSun** [LLK/scratch-extension-docs#5]
Hi.

I have a HID hardware with has 3 interfaces (or there will be trouble on Mac). The first interface in a keyboard, the second one is a gamepad and the third is a raw data one

![usb_interface](https://cloud.githubusercontent.com/assets/1385273/4086894/f195f48c-2f41-11e4-905f-4c04a96093b2.PNG)

I have a protocol to communicate with the third port. However when I open a device in scratch, the id is the first interface's. I don't have an option to choose the other interfaces.

However I can change my firmware to make the desired interface the first one and I made it work. I wish there is a parameter for interface.

if (e.hid) {
	var s = n.hid_list(),
		a = e.hid;
	for (var f = 0; f < s.length; f++) {
		var t = a[s[f].vendor_id + "_" + s[f].product_id];
		t && r[t]._deviceConnected(new m(s[f].path, t))
	}
}

Here is info from HIDAPI java library:

HIDDeviceInfo [path=\\?\hid#vid_94d8&pid_0055&mi_00#9&39c54981&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, vendor_id=38104, product_id=85, serial_number=?, release_number=1, manufacturer_string=Microchip Technology Inc., product_string=Analog Keyboard, usage_page=65280, usage=1, interface_number=0]
HIDDeviceInfo [path=\\?\hid#vid_94d8&pid_0055&mi_01#9&2201bd3c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, vendor_id=38104, product_id=85, serial_number=?, release_number=1, manufacturer_string=Microchip Technology Inc., product_string=Analog Keyboard, usage_page=1, usage=6, interface_number=1]
HIDDeviceInfo [path=\\?\hid#vid_94d8&pid_0055&mi_02#9&756a6ed&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, vendor_id=38104, product_id=85, serial_number=?, release_number=1, manufacturer_string=Microchip Technology Inc., product_string=Analog Keyboard, usage_page=1, usage=5, interface_number=2]

**Comment by khanning** [comment]
This was fixed on 1/28/15. This will require reinstallation of the [Scratch Browser Plugin](http://scratch.mit.edu/scratchr2/static/ext/download.html).

The interface number can now be accessed in the device object passed to _deviceConnected.
```
ext._deviceConnected = function(dev) {
  console.log(dev.info['interface_num']);
};
```
